/* Generated by u8g2fontgen - do not edit by hand.
 * Source config: fonts.yaml
 */

#ifndef CUSTOM_FONTS_H
#define CUSTOM_FONTS_H

#include <clib/u8g2.h>

extern const uint8_t custom_helvB24[] U8G2_FONT_SECTION("custom_helvB24");
extern const uint8_t custom_helvB12[] U8G2_FONT_SECTION("custom_helvB12");
extern const uint8_t custom_helvB18[] U8G2_FONT_SECTION("custom_helvB18");
extern const uint8_t custom_helvB08[] U8G2_FONT_SECTION("custom_helvB08");
extern const uint8_t custom_profont11[] U8G2_FONT_SECTION("custom_profont11");

#endif /* CUSTOM_FONTS_H */
